### PR TITLE
Added support for token based authentication to nightscout

### PR DESCRIPTION
**Pull request by Bull3time**
Support for token based authentication, but still allows open access without a token.
- Parses the provided url splitting out the token query parameter.
- Constructs the nightscout api calls with URLComponents and adds query parameters and the path component.

Nightguard previously crashed if a nightscout url with a token was provided.
- Added in check for incorrect content in response

### CODE REVIEW

**Comment by dhermanns** [comment]
Great - thanks for your support. I've left some questions.

**Comment by Bull3time** [comment]
No problem, happy to contribute! Where are your questions?

**Comment by dhermanns** [comment]
Directly on the code
Bull3time <notifications@github.com> schrieb am Fr. 9. Feb. 2018 um 23:01:

**Comment by Bull3time** [comment]
Sorry I can't see any comments in the code, I've not used github before but according to their help and reading reviews/comments on a pull request they should be showing inline to the code, but I cannot see anything.

**Comment by Bull3time** [comment]
Lol that explains it then, glad it wasn’t just me.

**Comment by dhermanns** [comment]
Do you have some comments now?

**Comment by Bull3time** [comment]
i suffered the same issue as you, appears there's a further step than just making comments, submitting them is also required :/

**Comment by dhermanns** [comment]
This PR has some conflicts due to Florian PR changes. Do you find some time to resolve it? Otherwise I will try to do it if I find some free time ;-)

**Comment by Bull3time** [comment]
Hey sorry I have been super busy of late, I'll look into this, I was planning on refactoring to add the parsing into the UserDefaults as you suggested anyway.

**Comment by Bull3time** [comment]
Ok merge conflicts are resolved.

**Comment by dhermanns** [comment]
Github is still complaining...

**Comment by Bull3time** [comment]
image
It is saying it's happy to me?

**Comment by dhermanns** [comment]
The PR #29 denotes for me:

image

**Comment by dhermanns** [comment]
Maybe you need to pull the latest changes from our master-Branch to your main-Branch.

**Comment by verunightscout** [comment]
I can test it, but I´m not developer ...

**Comment by Bull3time** [comment]
Ok no worries I’ll try and find some time

--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com <https://tutanota.com>

17. Jun 2018 06:24 by notifications@github.com <mailto:notifications@github.com>:

**Comment by dhermanns** [comment]
Hopefully nothing was broken during my merge efforts ;-) . I will have to activate security tokens in my backend and double check this...

**Pull request merged**
