### PR TITLE
Show raw BG value and noise level feature

### PR DESCRIPTION
**Pull request by florianpreknya**
This pull request will replace #32 (please read the description there). It completes the feature with the followings:
- raw BG values & noise level on phone and watch (pictures on #32)
- possibility to opt in/out in preferences (doubled by the fact that the raw bg & noise level are visible ONLY if the **rawbg** plugin is enabled on Nightscout Server and the corresponding data is received)
- save screen size on watch when displaying the raw bg

### CODE REVIEW

**Comment by dhermanns** [comment]
Great Florian! Can't wait to see how useful the raw values are.

**Comment by dhermanns** [comment]
This crashes for me on the watch right after opening it in the simulator. It happens in class NightscoutData here:

` required init(coder decoder: NSCoder) {

        guard let sgv = decoder.decodeObject(forKey: "sgv") as? String else {`

It crashes with a `Thread 1: EXC_BAD_ACCESS (code=1, address=0xf)`. Looks strange...

**Comment by dhermanns** [comment]
Strange - it vanished after restarting Xcode.

**Comment by dhermanns** [comment]
I enabled the rawbg feature for my nightscout backend, but the pebble cals values are still empty:

`{"status":[{"now":1529438064602}],"bgs":[{"sgv":"128","trend":4,"direction":"Flat","datetime":1529438047000,"bgdelta":0,"battery":"95"}],"cals":[]} `

Does this feature work with dexcom only?

**Comment by florianpreknya** [comment]
Yes, it's Dexcom specific, it's part of their BG estimation algorithm. This doc explains it in detail: http://www.nightscout.info/wiki/labs/interpreting-raw-dexcom-data
 
I forgot you said once you are on Medtronic... :(  But the next feature should be for Medtronic users! :)

BTW, I'll include this info in the explaining text from the preferences screen (the one under the "show raw BG" switch).

**Comment by florianpreknya** [comment]
Will do, I always have an eye on raw bg. :)
No, I'm not on the testers list. You can add me, just use the email from my github profile.

**Comment by Rmaw02** [comment]
Hi Florian, I had jumped into a previous conversation regarding raw from #32 . I have found raw on watchface useful on my apple watch. Just got my wife the 38mm and realized raw is not displayed. Are you still thinking about adding this to the smaller watch face (please). Simple in my mind, I know, but cant the displayed BG value simply be made a touch smaller to allow room to add raw value? Thanks for considering.

**Comment by florianpreknya** [comment]
Raw values should be visible on a 38mm watch also! Did you check if the "Show raw BG" switch in the phone app's Settings tab is on?

**Comment by Rmaw02** [comment]
Resolved - The show raw BG was switched on in the phone app, but was not displaying on the watch. After turning if off and back on, it is not being displayed. Thank you.

**Pull request merged**
