### PR TITLE
Configure fastlane to take screenshots in UI tests

### PR DESCRIPTION
**Pull request by makotila**
First attempt to use fastlane, could that be useful?

Changes:
* Product names for nightguardTests and nightguardUITests changed, to fix error "Multiple commands produce..."
* Podfile: added pods for testing
* added fastlane configuration
* added testTabsBars UI test to take some screenshots 
* removed testExample

Command to take screenshots:
```$ fastlane screenshots```
...
[21:32:16]: ▸ Test Succeeded
[21:32:22]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/en-US/iPhone 8-04-stats.png'...
[21:32:22]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/en-US/iPhone 11-03-alarms.png'...
[21:32:22]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/en-US/iPhone 11-04-stats.png'...
[21:32:22]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/en-US/iPhone 11-01-preferences.png'...
[21:32:22]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/en-US/iPhone 8-01-preferences.png'...
[21:32:22]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/en-US/iPhone 8-02-main.png'...
[21:32:22]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/en-US/iPhone 8-03-alarms.png'...
[21:32:22]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/en-US/iPhone 11-02-main.png'...

+-----------+-------+
| snapshot results  |
+-----------+-------+
| Device    | en-US |
+-----------+-------+
| iPhone 8  |  💚   |
| iPhone 11 |  💚   |
+-----------+-------+

[21:32:22]: Generating HTML Report
[21:32:22]: Successfully created HTML file with an overview of all the screenshots: '/Users/markus/work/nightguard/fastlane/screenshots/screenshots.html'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 2    | capture_screenshots | 324         |
+------+---------------------+-------------+

[21:32:25]: fastlane.tools finished successfully 🎉

### CODE REVIEW

**Comment by dhermanns** [comment]
Thanks Markus - that looks very promising!

Markus Kotilainen <notifications@github.com> schrieb am Di. 25. Feb. 2020
um 20:58:

**Comment by makotila** [comment]
Another branch where taken screenshots of both en-US and fi-fi languages :
https://github.com/makotila/nightguard/compare/fastlane...makotila:fastlane-and-finnish-translation

[17:21:27]: ▸ Test Succeeded
[17:21:33]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/fi-FI/iPhone 8-04-stats.png'...
[17:21:33]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/fi-FI/iPhone 11-03-alarms.png'...
[17:21:33]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/fi-FI/iPhone 11-04-stats.png'...
[17:21:33]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/fi-FI/iPhone 11-01-preferences.png'...
[17:21:33]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/fi-FI/iPhone 8-01-preferences.png'...
[17:21:33]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/fi-FI/iPhone 8-02-main.png'...
[17:21:33]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/fi-FI/iPhone 8-03-alarms.png'...
[17:21:33]: Copying '/Users/markus/work/nightguard/fastlane/screenshots/fi-FI/iPhone 11-02-main.png'...

+-----------+-------+-------+
|     snapshot results      |
+-----------+-------+-------+
| Device    | en-US | fi-FI |
+-----------+-------+-------+
| iPhone 8  |  💚   |  💚   |
| iPhone 11 |  💚   |  💚   |
+-----------+-------+-------+

**Comment by dhermanns** [comment]
Great. Works fine. I will add a Gemfile, since otherwise I will get a much too old version on macos. One more think that needs to be added: We need to change the nightscout URI before running the tests. Otherwise the screenshots don't contain any data.

**Comment by makotila** [comment]
Thanks.
Yeah, I noticed the same problem with nightscout test URI, alternatively it could be nice to use mocked NightscoutService for testing/screenshots, although it could need some refactoring as if I remember correctly there was singleton pattern in use, which makes it harder in practice.

**Comment by dhermanns** [comment]
Yes - mocking could be an option. But I think using the real backend could be something like an integration test, too.

**Pull request merged**
