### PR TITLE
Finnish fi-FI translation

### PR DESCRIPTION
**Pull request by makotila**
Adding support for a Finnish translation.

### CODE REVIEW

**Comment by dhermanns** [comment]
Thanks for your contribution. I‘m not a fan of localization, since this adds a lot of complexity and increases the maintenance costs.

I will have a look...

**Comment by makotila** [comment]
I understand your point. I'm not familiar with iOS and swift development and I don't know is there better way to do localizations. I think using strings as message keys is not ideal.

I see that localization makes code a little more complex and also translations need to be updated when new messages is added.

Base.lproj/Localizable.strings can be updated by command 
```find nightguard -name "*.swift" | xargs genstrings -o nightguard/Base.lproj```

**Comment by dhermanns** [comment]
My main problem is, that you will have to test the app after each release
for all supported languages. I already had hard crashes just because of too
long labels got too tiny. We will have something like fastline to automate
this. But I didn’t found enough time to introduce it.

**Comment by makotila** [comment]
Fastlane seems to be interesting, I will look at it

**Comment by dhermanns** [comment]
Are you already on my testflight mailing list? I would need someone who could constantly maintain the finnish translation in the future. May I add your eMail?

**Comment by makotila** [comment]
I'm not on the testflight mailing list, could you add me? I can maintain Finnish translations.

**Comment by dhermanns** [comment]
Amazing - leave me your email or send it to my twitter handle @h3rmanns if you like

**Comment by makotila** [comment]
> Amazing - leave me your email or send it to my twitter handle @h3rmanns if you like

Address is makotila at gmail dot com

**Comment by dhermanns** [comment]
@makotila : Could you have a look at the iPhone SE screens? Some finnish translations don't fit the screens there. E.g.

image

**Comment by makotila** [comment]
@dhermanns I'll check it and make corrections

**Comment by dhermanns** [comment]
Great - thanks Markus

**Pull request merged**
