### PR TITLE
Finnish texts can also fit on the iPhone SE (1.st) screen

### PR DESCRIPTION
**Pull request by makotila**

### CODE REVIEW

**Comment by dhermanns** [comment]
I don't know what it means - but looks great now ;-)

**Comment by dhermanns** [comment]
@makotila : I found some labels that had been missed so far and localized them to german. Could you have a look at my latest commit?

**Comment by makotila** [comment]
@dhermanns Yes, I created pull request https://github.com/nightscout/nightguard/pull/92

**Comment by dhermanns** [comment]
Great - thx!

**Comment by dhermanns** [comment]
I added a few more labels that have been missing on the Apple Watch. Could you have a look?

**Comment by makotila** [comment]
@dhermanns 
Added Finnish translations in PR https://github.com/nightscout/nightguard/pull/94

**Comment by dhermanns** [comment]
Saw that - thanks!

**Pull request merged**
