### PR TITLE
Show rawbg value and noise level

### PR DESCRIPTION
**Pull request by florianpreknya**
Being an ex-Pebble user, I missed the rawbg values & noise level on my apple watch. That's why I implemented this feature (I translated the nightscout rawbg plugin algorithm to swift for doing the math). It is very useful also when the noise level is heavy and there are no current bg values at all (the app will always show a 10mg/dl value on heavy noise), you can still have rawbg values.  
rawbg

Along with the activity indicator (the activity indicator is a little bigger, also the other elements were moved slowly to align with the new rawbg elements - only 8 points were cut from the graph height to make room):
rawbg-and-activity-indicator

Double tapping the bg area will show/hide the rawbg & noise info panel (probably this thing will change when I'll implement the settings in phone app - see bellow).

For the moment, it is visible only on the watch, I will do it for the phone app also next. The next move is to add a setting in phone app preferences/settings tab for letting the user opt if he wants to see the rawbg values (the same like on nightscout website has)
screen shot 2018-02-27 at 9 23 16 pm

The bigger plan is to keep also the filtered/unfiltered values in the BloodSugar class and show the rawbg also in the graph if the user opted for that (like in nightscout website). For that I'll have to request & keep the calibrations data for the last two days. So, it's a bigger fish to catch here for me... :)

### CODE REVIEW

**Comment by dhermanns** [comment]
Did you try that on a 38mm watch? I‘m sceptical whether the graph gets too small on it when we are loosing more space. 

I don’t use the raw bg values and normally we don‘t have to fight against noise. So I‘m not sure if this is something that is needed for many people.

Or do I miss something? What for a sensor do you use that you have to calculate rawbg values? What is your Uploader?

**Comment by florianpreknya** [comment]
My wife has a 38mm watch, it's not too small. I can obtain the lost 8 points back when the rawbg is not presented (already did it, but rolled back the code for more simplicity). 

I cannot tell if this information is valuable for many people. Me and my wife are monitoring our 1.8 yo daughter and have found it very useful for getting a more accurate trend (in case of treating a hypo, for eg) or to have values when the sensor reports heavy noise caused by pressure (or by getting old, etc).

I am using Dexcom G4 with Share linked on BT to an Android running the xDrip app.

**Comment by florianpreknya** [comment]
If you consider, I can make the pull request later, when the feature is complete with:
- phone app presenting also the rawbg (like the watch app)
- the graph previous height preserved (no height changes!) if rawbg elements are not presented
- settings in the phone app to control the rawbg visibility (default value being "Show RawBG when there is noise" - so by default it is not visible)

I'm just thinking.. Can we find somehow if this feature is needed by more? Otherwise, I can just keep it for myself.

**Comment by dhermanns** [comment]
Sounds good to me: If you have the feature toggleable, everybody can decide on their own.
It would be nice to know how many people are using this in nightscout.

But maybe I can learn something and will love this feature after practicing with it ;-).
So please let me know when I can merge the whole feature.

**Comment by Rmaw02** [comment]
Ex-pebbler here too. Same set up as described by Florian. New to apple watch and found Nightguard as best/only option. Most interested in viewing BG (in real time) from watch face (via complication). Is the ability to add rawbg display (on watchface complication) still being perused? Also, what is the expected frequency of value updates. My values seem to update anywhere between 10-30 min unless I open the watch app. Coming from pebble, i am used to the at a glance, up to date (updates every 5 min same as dex) bg reading. I tried the nightscouter watch app and like the rawbg display (and noise level), but this does not seem to update on the watchface complication at all (unless forced to update).

For the record, i know nothing about programming or how to make this work and very much appreciate the efforts being put into this.

file-1

**Comment by florianpreknya** [comment]
What can I say? Welcome to the Apple world, then! :)
Maybe you'll be a little disappointed to hear that the real-time Pebble watch-face update is not possible on Apple watch. This is not because we cannot do it, but because the watchOS is too greedy with its resources and doesn't permit too many updates while an app is in background. And too many complication updates, also. Although the background time and complication updates are scheduled by the nightguard app from 5 in 5 minutes, the watchOS will decide if the app deserves to get that background time to query the new BG values and update its complication. Usually, an app receives 4 background updates / hour.. but this number can vary, it depends how many apps requested background time, if the app consumed its quota, etc. Only Apple has the algorithm. Some times the app receives 2 updates/hour, some times 8 or 10 or ... N. 
About the raw bg values & noise level, I have started a feature branch that is still in development, I hope will be ready in 2-3 weeks, maybe even sooner. You will be able to see the rawbg and noise level in the phone & watch app (check the above images). I didn't intent to show it on a complication, but it is possible to have it also there. Keep in touch! 👍

**Comment by florianpreknya** [comment]
This PR will be transformed into #46 and will be closed.

**Pull request closed without merging**
